name: CI

on:
  push:
    paths:
      - '**/*.ps1'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: pwsh ./.github/workflows/CI.ps1
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ps12exe.exe
